package com.subgrab.app.data

import com.subgrab.app.domain.Source
import com.subgrab.app.domain.SubtitleLanguage
import com.subgrab.app.domain.VideoItem
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import org.schabi.newpipe.extractor.NewPipe
import org.schabi.newpipe.extractor.playlist.PlaylistExtractor
import org.schabi.newpipe.extractor.channel.ChannelExtractor
import org.schabi.newpipe.extractor.stream.StreamInfoItem

class NewPipeMetadataProvider {
    companion object {
        private const val MAX_VIDEOS = 50
    }

    suspend fun fetch(url: String): Result<Pair<Source, List<VideoItem>>> = withContext(Dispatchers.IO) {
        runCatching {
            val service = NewPipe.getServiceByUrl(url)
                ?: error("Khong ho tro link nay")
            val trimmed = url.trim()

            when {
                trimmed.contains("watch?v=") || trimmed.contains("youtu.be/") -> fetchSingleVideo(service, trimmed)
                trimmed.contains("/playlist?") -> fetchPlaylist(service, trimmed)
                trimmed.contains("/@") || trimmed.contains("/c/") || trimmed.contains("/channel/") -> fetchChannel(service, trimmed)
                else -> error("Link khong duoc ho tro: $trimmed")
            }
        }
    }

    private fun fetchSingleVideo(service: org.schabi.newpipe.extractor.StreamingService, url: String): Pair<Source, List<VideoItem>> {
        val extractor = service.getStreamExtractor(url)
        extractor.fetchPage()
        val videoId = extractor.id
        val title = extractor.name ?: "Video $videoId"
        val duration = extractor.length
        val subs = extractor.subtitlesDefault.map { track ->
            SubtitleLanguage(track.languageTag, track.isAutoGenerated, track.displayLanguageName)
        }.distinctBy { it.code to it.isAuto }
        val video = VideoItem(
            index = 1,
            videoId = videoId,
            title = title,
            durationSec = duration.toInt(),
            availableSubs = subs,
            isSelected = false
        )
        val source = Source(id = videoId, url = url, title = title, originalTotalVideos = 1)
        return source to listOf(video)
    }

    private fun fetchPlaylist(service: org.schabi.newpipe.extractor.StreamingService, url: String): Pair<Source, List<VideoItem>> {
        val extractor: PlaylistExtractor = service.getPlaylistExtractor(url)
        extractor.fetchPage()
        val playlistId = extractor.id ?: "playlist"
        val playlistName = extractor.name ?: "Playlist $playlistId"
        val items = extractor.initialPage.items.orEmpty().take(MAX_VIDEOS)
        val videos = items.mapIndexedNotNull { idx, item ->
            buildVideoItem(idx, item, service)
        }
        val source = Source(id = playlistId, url = url, title = playlistName, originalTotalVideos = extractor.initialPage.items?.size ?: videos.size)
        return source to videos
    }

    private fun fetchChannel(service: org.schabi.newpipe.extractor.StreamingService, url: String): Pair<Source, List<VideoItem>> {
        val extractor: ChannelExtractor = service.getChannelExtractor(url)
        extractor.fetchPage()
        val channelId = extractor.id ?: "channel"
        val channelName = extractor.name ?: "Channel $channelId"
        val items = extractor.initialPage.items.orEmpty().take(MAX_VIDEOS)
        val videos = items.mapIndexedNotNull { idx, item ->
            buildVideoItem(idx, item, service)
        }
        val source = Source(id = channelId, url = url, title = channelName, originalTotalVideos = extractor.initialPage.items?.size ?: videos.size)
        return source to videos
    }

    private fun buildVideoItem(index: Int, item: StreamInfoItem, service: org.schabi.newpipe.extractor.StreamingService): VideoItem? {
        val videoId = runCatching { item.url?.substringAfter("v=")?.substringBefore("&") }.getOrNull() ?: return null
        if (videoId.isBlank()) return null
        val title = item.name ?: "Video $videoId"
        val duration = runCatching { item.duration }.getOrDefault(0L).toInt()
        return VideoItem(
            index = index + 1,
            videoId = videoId,
            title = title,
            durationSec = duration,
            availableSubs = emptyList(),
            isSelected = false
        )
    }
}