package com.subgrab.app.data

import android.content.Context
import com.subgrab.app.domain.OutputFormat
import com.subgrab.app.domain.SubtitleLanguage
import com.subgrab.app.domain.VideoItem
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import org.schabi.newpipe.extractor.MediaFormat
import org.schabi.newpipe.extractor.NewPipe
import org.schabi.newpipe.extractor.localization.ContentCountry
import org.schabi.newpipe.extractor.localization.Localization
import java.io.File
import java.net.HttpURLConnection
import java.net.URL

class NewPipeSubtitleProvider(context: Context) {
    init {
        synchronized(NewPipeSubtitleProvider::class.java) {
            if (!initialized) {
                NewPipe.init(NewPipeDownloader(), Localization("en", "US"), ContentCountry("US"))
                initialized = true
            }
        }
    }

    suspend fun list(videoUrl: String): Result<List<SubtitleLanguage>> = withContext(Dispatchers.IO) {
        runCatching {
            val extractor = NewPipe.getServiceByUrl(videoUrl).getStreamExtractor(videoUrl)
            extractor.fetchPage()
            extractor.getSubtitlesDefault().map { track ->
                SubtitleLanguage(track.getLanguageTag(), track.isAutoGenerated(), track.getDisplayLanguageName())
            }.distinctBy { it.code to it.isAuto }
        }
    }

    suspend fun download(video: VideoItem, languages: List<String>, formats: Set<OutputFormat>, outputDir: File): Result<List<File>> = withContext(Dispatchers.IO) {
        runCatching {
            val url = "https://www.youtube.com/watch?v=${video.videoId}"
            val extractor = NewPipe.getServiceByUrl(url).getStreamExtractor(url)
            extractor.fetchPage()
            val tracks = extractor.getSubtitles(MediaFormat.VTT)
                .filter { track -> languages.any { wanted -> track.getLanguageTag().equals(wanted, true) || track.getLanguageTag().startsWith("$wanted-") } }
            require(tracks.isNotEmpty()) { "NewPipeExtractor không tìm thấy subtitle phù hợp" }
            tracks.map { track ->
                val text = downloadText(track.content)
                val srt = vttToSrt(text)
                val extension = if (formats.contains(OutputFormat.SRT)) "srt" else "txt"
                val content = if (extension == "txt") com.subgrab.app.domain.SrtToTxtConverter.convert(srt) else srt
                File(outputDir, "${video.index.toString().padStart(3, '0')} - ${com.subgrab.app.domain.FileNameSanitizer.sanitize(video.title)}-${track.getLanguageTag()}.$extension").apply {
                    parentFile?.mkdirs()
                    writeText(content)
                }
            }
        }
    }

    private fun downloadText(url: String): String {
        val connection = URL(url).openConnection() as HttpURLConnection
        connection.connectTimeout = 15_000
        connection.readTimeout = 30_000
        connection.setRequestProperty("User-Agent", "Mozilla/5.0 (Linux; Android 13) AppleWebKit/537.36 Chrome/124 Mobile Safari/537.36")
        check(connection.responseCode in 200..299) { "Subtitle HTTP ${connection.responseCode}" }
        return connection.inputStream.bufferedReader().use { it.readText() }
    }

    private fun vttToSrt(input: String): String {
        var counter = 1
        return input.lineSequence().filterNot { it == "WEBVTT" || it.startsWith("NOTE") || it.startsWith("Kind:") || it.startsWith("Language:") }.joinToString("\n") { line ->
            if (line.contains(" --> ")) "${counter++}\n${line.replace('.', ',')}" else line
        }.replace(Regex("\n{3,}"), "\n\n").trim() + "\n"
    }

    companion object { @Volatile private var initialized = false }
}
