package com.subgrab.app.data

import android.content.Context
import com.subgrab.app.domain.OutputFormat
import com.subgrab.app.domain.Source
import com.subgrab.app.domain.SubtitleLanguage
import com.subgrab.app.domain.VideoItem
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import org.schabi.newpipe.extractor.MediaFormat
import org.schabi.newpipe.extractor.NewPipe
import org.schabi.newpipe.extractor.localization.ContentCountry
import org.schabi.newpipe.extractor.localization.Localization
import org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor
import org.schabi.newpipe.extractor.stream.StreamInfoItem
import java.io.File

class NewPipeSubtitleProvider(context: Context) {
    private val downloader = NewPipeDownloader()
    private val poTokenProvider = NewPipePoTokenProvider(context.applicationContext, downloader)
    init {
        synchronized(NewPipeSubtitleProvider::class.java) {
            if (!initialized) {
                NewPipe.init(downloader, Localization("en", "US"), ContentCountry("US"))
                YoutubeStreamExtractor.setPoTokenProvider(poTokenProvider)
                initialized = true
            }
        }
    }

    suspend fun list(videoUrl: String): Result<List<SubtitleLanguage>> = withContext(Dispatchers.IO) {
        runCatching {
            DebugLog.d("SUB_LIST start url=${videoUrl.substringBefore("?")}")
            val extractor = NewPipe.getServiceByUrl(videoUrl).getStreamExtractor(videoUrl)
            DebugLog.d("SUB_LIST fetchPage")
            extractor.fetchPage()
            DebugLog.d("SUB_LIST fetchPage OK; parsing captions")
            extractor.getSubtitlesDefault().map { track ->
                SubtitleLanguage(track.getLanguageTag(), track.isAutoGenerated(), track.getDisplayLanguageName())
            }.distinctBy { it.code to it.isAuto }
        }.onFailure { DebugLog.e("SUB_LIST failed", it) }
    }

    suspend fun download(video: VideoItem, languages: List<String>, formats: Set<OutputFormat>, outputDir: File): Result<List<File>> = withContext(Dispatchers.IO) {
        runCatching {
            DebugLog.d("SUB_DOWNLOAD start video=${video.videoId}")
            val url = "https://www.youtube.com/watch?v=${video.videoId}"
            val extractor = NewPipe.getServiceByUrl(url).getStreamExtractor(url)
            DebugLog.d("SUB_DOWNLOAD fetchPage")
            extractor.fetchPage()
            DebugLog.d("SUB_DOWNLOAD fetchPage OK; parsing captions")
            val tracks = extractor.getSubtitles(MediaFormat.VTT)
                .filter { track -> languages.any { wanted -> track.getLanguageTag().equals(wanted, true) || track.getLanguageTag().startsWith("$wanted-") } }
            DebugLog.d("SUB_DOWNLOAD tracks=${tracks.size}")
            require(tracks.isNotEmpty()) { "NewPipeExtractor không tìm thấy subtitle phù hợp" }
            tracks.map { track ->
                val text = downloader.fetchText(track.content, url)
                val srt = vttToSrt(text)
                val extension = if (formats.contains(OutputFormat.SRT)) "srt" else "txt"
                val content = if (extension == "txt") com.subgrab.app.domain.SrtToTxtConverter.convert(srt) else srt
                File(outputDir, "${video.index.toString().padStart(3, '0')} - ${com.subgrab.app.domain.FileNameSanitizer.sanitize(video.title)}-${track.getLanguageTag()}.$extension").apply {
                    parentFile?.mkdirs()
                    writeText(content)
                }
            }
        }.onFailure { DebugLog.e("SUB_DOWNLOAD failed", it) }
    }

    suspend fun fetchSource(url: String): Result<Pair<Source, List<VideoItem>>> = withContext(Dispatchers.IO) {
        runCatching {
            val service = NewPipe.getServiceByUrl(url)
            val isList = url.contains("playlist") || url.contains("channel") || url.contains("/c/") || url.contains("/@") || url.contains("list=")
            if (isList) {
                val extractor = service.getPlaylistExtractor(url)
                extractor.fetchPage()
                val streams = extractor.getInitialPage().items.filterIsInstance<StreamInfoItem>().take(50)
                val videos = streams.mapIndexed { index, item ->
                    VideoItem(
                        index + 1,
                        youtubeVideoId(item.getUrl()),
                        item.getName(),
                        item.getDuration().toInt(),
                        emptyList()
                    )
                }
                Source(url, url, extractor.getName(), videos.size) to videos
            } else {
                // Do not fetch the full StreamInfo here. On older Android/YouTube
                // combinations that request can fail with a stream-related 403,
                // even though the subtitle endpoint still works. NewPipe itself
                // treats those concerns separately.
                val videoId = youtubeVideoId(url)
                val video = VideoItem(1, videoId, videoId, 0, emptyList())
                Source(url, url, videoId, 1) to listOf(video)
            }
        }
    }

    private fun youtubeVideoId(url: String): String {
        val uri = android.net.Uri.parse(url)
        return uri.getQueryParameter("v")
            ?: uri.pathSegments.lastOrNull()?.takeIf { it.isNotBlank() }
            ?: url
    }

    private fun vttToSrt(input: String): String {
        var counter = 1
        return input.lineSequence().filterNot { it == "WEBVTT" || it.startsWith("NOTE") || it.startsWith("Kind:") || it.startsWith("Language:") }.joinToString("\n") { line ->
            if (line.contains(" --> ")) "${counter++}\n${line.replace('.', ',')}" else line
        }.replace(Regex("\n{3,}"), "\n\n").trim() + "\n"
    }

    companion object { @Volatile private var initialized = false }
}
