package com.subgrab.app.data

import android.content.Context
import android.net.Uri
import com.subgrab.app.domain.Source
import com.subgrab.app.domain.SubtitleLanguage
import com.subgrab.app.domain.VideoItem
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import org.schabi.newpipe.extractor.MediaFormat
import org.schabi.newpipe.extractor.NewPipe
import org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor
import org.schabi.newpipe.extractor.stream.StreamExtractor
import org.schabi.newpipe.extractor.stream.StreamInfoItem

class NewPipeExtractorClient(context: Context) {
    private val downloader = NewPipeDownloader()
    private val poTokenProvider = NewPipePoTokenProvider(context.applicationContext, downloader)

    init {
        synchronized(NewPipeExtractorClient::class.java) {
            if (!initialized) {
                NewPipe.init(
                    downloader,
                    org.schabi.newpipe.extractor.localization.Localization("en", "US"),
                    org.schabi.newpipe.extractor.localization.ContentCountry("US")
                )
                YoutubeStreamExtractor.setPoTokenProvider(poTokenProvider)
                initialized = true
            }
        }
    }

    suspend fun extractSource(url: String): Result<Pair<Source, List<VideoItem>>> = withContext(Dispatchers.IO) {
        runCatching {
            val service = NewPipe.getServiceByUrl(url)
            val isList = url.contains("playlist") || url.contains("channel") ||
                url.contains("/c/") || url.contains("/@") || url.contains("list=")

            if (isList) {
                val extractor = service.getPlaylistExtractor(url)
                extractor.fetchPage()
                val streams = extractor.getInitialPage().items.filterIsInstance<StreamInfoItem>().take(50)
                val videos = streams.mapIndexed { index, item ->
                    VideoItem(
                        index = index + 1,
                        videoId = youtubeVideoId(item.getUrl()),
                        title = item.getName(),
                        durationSec = item.getDuration().toInt(),
                        availableSubs = emptyList(),
                        subtitleChecked = false
                    )
                }
                Source(url, url, extractor.getName(), videos.size) to videos
            } else {
                val extractor = service.getStreamExtractor(url)
                extractor.fetchPage()
                val id = youtubeVideoId(url)
                val title = runCatching { extractor.getName() }.getOrDefault(id)
                Source(url, url, title, 1) to listOf(
                    VideoItem(
                        index = 1,
                        videoId = id,
                        title = title,
                        durationSec = 0,
                        availableSubs = emptyList(),
                        subtitleChecked = false
                    )
                )
            }
        }
    }

    suspend fun listSubtitles(videoUrl: String): Result<List<SubtitleLanguage>> = withContext(Dispatchers.IO) {
        runCatching {
            val extractor = streamExtractor(videoUrl)
            extractor.fetchPage()
            extractor.getSubtitlesDefault()
                .map { track ->
                    SubtitleLanguage(
                        track.getLanguageTag(),
                        track.isAutoGenerated(),
                        track.getDisplayLanguageName()
                    )
                }
                .distinctBy { it.code to it.isAuto }
        }
    }

    fun streamExtractor(videoUrl: String): StreamExtractor =
        NewPipe.getServiceByUrl(videoUrl).getStreamExtractor(videoUrl)

    fun subtitles(videoUrl: String, format: MediaFormat = MediaFormat.VTT) =
        streamExtractor(videoUrl).getSubtitles(format)

    suspend fun search(query: String): Result<Pair<Source, List<VideoItem>>> = withContext(Dispatchers.IO) {
        runCatching {
            val encoded = Uri.encode(query.trim())
            val url = "https://www.youtube.com/results?search_query=" + encoded
            val extractor = NewPipe.getServiceByUrl(url).getSearchExtractor(url)
            extractor.fetchPage()
            val videos = extractor.getInitialPage().items
                .filterIsInstance<StreamInfoItem>()
                .take(50)
                .mapIndexed { index, item ->
                    VideoItem(
                        index = index + 1,
                        videoId = youtubeVideoId(item.getUrl()),
                        title = item.getName(),
                        durationSec = item.getDuration().toInt(),
                        availableSubs = emptyList(),
                        subtitleChecked = false
                    )
                }
            Source(url, url, "Tìm kiếm: " + query.trim(), videos.size) to videos
        }
    }

    private fun youtubeVideoId(url: String): String {
        val uri = Uri.parse(url)
        return uri.getQueryParameter("v")
            ?: uri.pathSegments.lastOrNull()?.takeIf { it.isNotBlank() }
            ?: url
    }

    companion object {
        @Volatile private var initialized = false
    }
}
