package com.subgrab.app.data

import android.content.Context
import android.net.Uri
import java.text.Normalizer
import com.subgrab.app.domain.Source
import com.subgrab.app.domain.SubtitleLanguage
import com.subgrab.app.domain.VideoItem
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import org.schabi.newpipe.extractor.MediaFormat
import org.schabi.newpipe.extractor.NewPipe
import org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor
import org.schabi.newpipe.extractor.stream.StreamExtractor
import org.schabi.newpipe.extractor.stream.StreamInfoItem

class NewPipeExtractorClient(context: Context) {
    private val downloader = NewPipeDownloader()
    private val poTokenProvider = NewPipePoTokenProvider(context.applicationContext, downloader)

    init {
        synchronized(NewPipeExtractorClient::class.java) {
            if (!initialized) {
                NewPipe.init(
                    downloader,
                    org.schabi.newpipe.extractor.localization.Localization("en", "US"),
                    org.schabi.newpipe.extractor.localization.ContentCountry("US")
                )
                YoutubeStreamExtractor.setPoTokenProvider(poTokenProvider)
                initialized = true
            }
        }
    }

    suspend fun extractSource(url: String): Result<Pair<Source, List<VideoItem>>> = withContext(Dispatchers.IO) {
        runCatching {
            val service = NewPipe.getServiceByUrl(url)
            val isList = url.contains("playlist") || url.contains("channel") ||
                url.contains("/c/") || url.contains("/@") || url.contains("list=")

            if (isList) {
                val extractor = service.getPlaylistExtractor(url)
                extractor.fetchPage()
                val streams = extractor.getInitialPage().items.filterIsInstance<StreamInfoItem>().take(50)
                val videos = streams.mapIndexed { index, item ->
                    VideoItem(
                        index = index + 1,
                        videoId = youtubeVideoId(item.getUrl()),
                        title = item.getName(),
                        durationSec = item.getDuration().toInt(),
                        availableSubs = emptyList(),
                        subtitleChecked = false
                    )
                }
                Source(url, url, extractor.getName(), videos.size) to videos
            } else {
                val extractor = service.getStreamExtractor(url)
                extractor.fetchPage()
                val id = youtubeVideoId(url)
                val title = runCatching { extractor.getName() }.getOrDefault(id)
                Source(url, url, title, 1) to listOf(
                    VideoItem(
                        index = 1,
                        videoId = id,
                        title = title,
                        durationSec = 0,
                        availableSubs = emptyList(),
                        subtitleChecked = false
                    )
                )
            }
        }
    }

    suspend fun listSubtitles(videoUrl: String): Result<List<SubtitleLanguage>> = withContext(Dispatchers.IO) {
        runCatching {
            val extractor = streamExtractor(videoUrl)
            extractor.fetchPage()
            extractor.getSubtitlesDefault()
                .map { track ->
                    SubtitleLanguage(
                        track.getLanguageTag(),
                        track.isAutoGenerated(),
                        track.getDisplayLanguageName()
                    )
                }
                .distinctBy { it.code to it.isAuto }
        }
    }

    fun streamExtractor(videoUrl: String): StreamExtractor =
        NewPipe.getServiceByUrl(videoUrl).getStreamExtractor(videoUrl)

    fun subtitles(videoUrl: String, format: MediaFormat = MediaFormat.VTT) =
        streamExtractor(videoUrl).getSubtitles(format)

    suspend fun search(query: String): Result<Pair<Source, List<VideoItem>>> = withContext(Dispatchers.IO) {
        runCatching {
            val cleanQuery = query.trim()
            require(cleanQuery.isNotBlank()) { "Vui lòng nhập từ khóa" }

            // Keep the same search construction used by the keyword branch.
            // Building SearchQueryHandler explicitly avoids NewPipeExtractor
            // changing/normalizing the query while constructing the handler.
            val encodedQuery = Uri.encode(cleanQuery)
            val searchUrl = "https://www.youtube.com/results?search_query=" + encodedQuery
            val searchHandler = org.schabi.newpipe.extractor.linkhandler.SearchQueryHandler(
                searchUrl,
                searchUrl,
                cleanQuery,
                emptyList(),
                ""
            )

            val service = org.schabi.newpipe.extractor.ServiceList.YouTube
            val extractor = service.getSearchExtractor(searchHandler)
            extractor.fetchPage()

            // Preserve NewPipeExtractor's own result order. Do not rank, filter,
            // normalize titles, or otherwise implement a second search engine.
            val items = extractor.getInitialPage().items
                .filterIsInstance<StreamInfoItem>()
                .take(50)

            val videos = items.mapIndexed { index, item ->
                VideoItem(
                    index = index + 1,
                    videoId = youtubeVideoId(item.getUrl()),
                    title = item.getName(),
                    durationSec = item.getDuration().coerceAtLeast(0L)
                        .coerceAtMost(Int.MAX_VALUE.toLong()).toInt(),
                    availableSubs = emptyList(),
                    isSelected = false,
                    subtitleChecked = false,
                    channelTitle = item.getUploaderName().orEmpty(),
                    publishedAt = item.getTextualUploadDate().orEmpty(),
                    viewCount = item.getViewCount().takeIf { it >= 0 },
                    thumbnailUrl = item.getThumbnails().firstOrNull()?.getUrl().orEmpty()
                )
            }

            val source = Source(
                id = "keyword:" + cleanQuery,
                url = searchUrl,
                title = cleanQuery,
                originalTotalVideos = videos.size
            )
            source to videos
        }
    }

    private fun youtubeVideoId(url: String): String {
        val uri = Uri.parse(url)
        return uri.getQueryParameter("v")
            ?: uri.pathSegments.lastOrNull()?.takeIf { it.isNotBlank() }
            ?: url
    }

    companion object {
        @Volatile private var initialized = false
    }
}
