package com.subgrab.app.data

import com.subgrab.app.domain.*
import com.subgrab.app.data.repository.KnowledgeRepository
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import org.schabi.newpipe.extractor.MediaFormat
import java.io.File

class SubtitleDownloader(
    private val extractorClient: NewPipeExtractorClient,
    private val downloader: NewPipeDownloader,
    private val knowledgeRepository: KnowledgeRepository? = null
) {
    suspend fun download(
        video: VideoItem,
        config: DownloadConfig,
        outputDir: File
    ): Result<List<File>> = withContext(Dispatchers.IO) {
        runCatching {
            val url = "https://www.youtube.com/watch?v=" + video.videoId
            val extractor = extractorClient.fetchSubtitleExtractor(url)

            val tracks = extractor.getSubtitles(MediaFormat.VTT)
                .filter { track ->
                    config.languages.any { wanted ->
                        track.getLanguageTag().equals(wanted, true) ||
                            track.getLanguageTag().startsWith(wanted + "-")
                    }
                }
                .sortedBy { if (config.preferManual && it.isAutoGenerated()) 1 else 0 }

            if (tracks.isEmpty()) {
                throw SubtitleFailure(
                    FailureType.LANGUAGE_UNAVAILABLE,
                    "NewPipeExtractor không tìm thấy subtitle phù hợp"
                )
            }

            val files = mutableListOf<File>()
            val roomTrack = selectRoomTrack(tracks, config.languages, config.preferManual)
            tracks.forEach { track ->
                val rawVtt = downloader.fetchText(track.content, url)
                val cues = SubtitleParser.parseWebVtt(rawVtt)
                val language = track.getLanguageTag()
                val base = video.index.toString().padStart(3, '0') +
                    " - " + FileNameSanitizer.sanitize(video.title) + "-" + language

                if (OutputFormat.SRT in config.formats) {
                    files += write(
                        outputDir,
                        "$base.srt",
                        SubtitleFormatter.format(cues, config.timestampMode)
                    )
                }
                val cleanText = SubtitleFormatter.format(cues, SubtitleTimestampMode.WITHOUT_TIMESTAMP)
                if (OutputFormat.TXT in config.formats) {
                    files += write(outputDir, "$base.txt", cleanText)
                }
                if (track === roomTrack) {
                    runCatching { knowledgeRepository?.saveTranscript(video.videoId, cleanText, language) }
                }
            }
            files
        }
    }


    suspend fun fetchAndPersistTranscript(
        videoId: String,
        languages: List<String>,
        preferManual: Boolean,
        requestedLanguage: String? = null,
        requestedFormat: OutputFormat = OutputFormat.TXT,
        forceRefresh: Boolean = false
    ): Result<String> = withContext(Dispatchers.IO) {
        runCatching {
            val existing = knowledgeRepository?.getTranscript(videoId)
            val wantedLanguage = requestedLanguage
                ?: existing?.language?.takeIf { stored ->
                    languages.any { it.equals(stored, true) || stored.startsWith(it + "-", true) }
                }
                ?: languages.firstOrNull { it.equals("en", true) }
                ?: languages.firstOrNull()

            val languageMatches = wantedLanguage != null && existing?.language?.let { stored ->
                stored.equals(wantedLanguage, true) || stored.startsWith(wantedLanguage + "-", true)
            } == true

            if (!forceRefresh && requestedFormat == OutputFormat.TXT && languageMatches && !existing?.content.isNullOrBlank()) {
                return@runCatching existing!!.language.orEmpty()
            }

            val url = "https://www.youtube.com/watch?v=" + videoId
            val extractor = extractorClient.fetchSubtitleExtractor(url)
            val tracks = extractor.getSubtitles(MediaFormat.VTT)
                .filter { track ->
                    wantedLanguage == null || track.getLanguageTag().equals(wantedLanguage, true) ||
                        track.getLanguageTag().startsWith(wantedLanguage + "-")
                }
                .sortedBy { if (preferManual && it.isAutoGenerated()) 1 else 0 }

            if (tracks.isEmpty()) {
                throw SubtitleFailure(FailureType.LANGUAGE_UNAVAILABLE, "Không tìm thấy subtitle phù hợp")
            }

            val track = tracks.first()
            val rawVtt = downloader.fetchText(track.content, url)
            val cues = SubtitleParser.parseWebVtt(rawVtt)
            val cleanText = SubtitleFormatter.format(cues, SubtitleTimestampMode.WITHOUT_TIMESTAMP)
            val language = track.getLanguageTag()

            if (requestedFormat == OutputFormat.TXT) {
                val overwrite = forceRefresh && languageMatches
                knowledgeRepository?.saveTranscript(videoId, cleanText, language, overwrite)
            }
            language
        }
    }

    private fun selectRoomTrack(
        tracks: List<org.schabi.newpipe.extractor.stream.SubtitlesStream>,
        configuredLanguages: List<String>,
        preferManual: Boolean
    ): org.schabi.newpipe.extractor.stream.SubtitlesStream {
        if (configuredLanguages.size == 1) {
            val wanted = configuredLanguages.first()
            return tracks.first { it.getLanguageTag().equals(wanted, true) || it.getLanguageTag().startsWith(wanted + "-") }
        }
        val english = tracks.filter {
            it.getLanguageTag().equals("en", true) || it.getLanguageTag().startsWith("en-")
        }
        if (english.isNotEmpty()) {
            return english.firstOrNull { preferManual && !it.isAutoGenerated() } ?: english.first()
        }
        return tracks.firstOrNull { preferManual && !it.isAutoGenerated() } ?: tracks.first()
    }

    private fun write(directory: File, name: String, content: String): File =
        runCatching {
            File(directory, name).apply {
                parentFile?.mkdirs()
                writeText(content)
            }
        }.getOrElse { throw StorageFailure("Không thể ghi subtitle: " + name, it) }
}

class SubtitleFailure(
    val type: FailureType,
    message: String
) : RuntimeException(message)
